services:
  redis:
    image: redis
    volumes:
      - db_data:/data
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 10s
      retries: 3

  python:
    depends_on:
      redis:
        condition: service_healthy
    image: python-api
    ports:
      - 5002:5002
    restart: always
    environment:
      REDIS_HOST: redis
volumes:
  db_data:
  